apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::393323650493:role/digital-library-prod-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
      data:
  mapRoles: |
    - rolearn: arn:aws:iam::393323650493:role/digital-library-prod-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::393323650493:user/github-actions-cicd
      username: github-actions-cicd
      groups:
        - system:masters

kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-19T18:54:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6942"
  uid: 3625547d-7a4a-4874-98e8-aac7d353d19e
