apiVersion: v1
kind: ServiceAccount
metadata:
  name: library-sa
  namespace: library
  annotations:
    # IRSA — links this ServiceAccount to the IAM role that allows
    # S3, SQS, and Secrets Manager access.
    # Value from: terraform output app_pod_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::393323650493:role/digital-library-prod-app-pod-role"
